name: Deploy Railway (Somente bot.py e Procfile)

on:
  push:
    branches:
      - main  # Executa apenas na branch principal
    paths:
      - 'bot.py'     # 🚀 Executa o workflow se bot.py for alterado
      - 'Procfile'   # 🚀 Executa o workflow se Procfile for alterado

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Instalar Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Autenticar no Railway
        run: railway auth --token=${{ secrets.RAILWAY_TOKEN }}

      - name: Fazer Deploy no Railway
        run: railway up
