name: Deploy Railway (Somente bot.py e Procfile)

on:
  push:
    branches:
      - main             # Define que isso acontece apenas na branch principal
    paths-ignore:
      - '**'             # Ignora todas as alterações por padrão
      - '!bot.py'        # 🚀 Executa se bot.py for alterado
      - '!Procfile'      # 🚀 Executa se Procfile for alterado

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Instalar Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Autenticar no Railway
        run: railway auth --token=${{ secrets.RAILWAY_TOKEN }}

      - name: Fazer Deploy no Railway
        run: railway up
